name: Main

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: make build
      - name: Run vet & lint
        run: |
          go vet .
          golint .
      - uses: actions/upload-artifact@v2
        with:
          name: app_${{ github.sha }}
          path: ./pi-test
      # send notification that asset is uploaded. need to get url, otherwise server will have to query and find it
      - name: Trigger pi-app-updater
        run: |
          curl -X POST -d '{"sha":"${{ github.sha }}","repository":"${{ github.repository }}","artifact":"app_${{ github.sha }}"}' https://58b3-2601-603-400-926-81d7-721-8426-f1f0.ngrok.io/push
