name: Main Deploy

on:
  workflow_run:
    workflows: ["Main Build"]
    branches: [main]
    types: 
      - completed

jobs:
  pi_app_deployer:
    runs-on: ubuntu-latest
    name: Pi App Deployer
    steps:
      - uses: actions/checkout@v2
      - name: Get deployer vars
        id: vars
        run: ./scripts/get-deployer-vars.sh
        env:
          PI_APP_DEPLOYER_API_KEY_STAGING: ${{ secrets.PI_APP_DEPLOYER_API_KEY_STAGING }}
          PI_APP_DEPLOYER_API_KEY_PROD: ${{ secrets.PI_APP_DEPLOYER_API_KEY_PROD }}
      - name: Deploy Application
        uses: andrewmarklloyd/pi-app-deployer-action@main
        env:
          PI_APP_DEPLOYER_API_KEY: ${{ steps.vars.outputs.PI_APP_DEPLOYER_API_KEY }}
        with:
          repoName: andrewmarklloyd/pi-test
          manifestName: pi-test-amd64
          host: https://${{ steps.vars.outputs.DEPLOYER_APP }}.herokuapp.com
          artifactName: app_${{ github.sha }}
