name: Main Deploy

on:
  workflow_run:
    workflows: ["Main Build"]
    branches: [main]
    types: 
      - completed

jobs:
  pi_app_deployer:
    runs-on: ubuntu-latest
    name: Pi App Deployer
    steps:
      - uses: actions/checkout@v2
      - name: Get deployer vars
        id: vars
        run: |
          line=$(tail -n 1 test/integration-trigger.txt)
          arr=($(echo $line | tr ";" "\n"))
          host=${arr[1]}
          echo "::set-output name=DEPLOYER_HOST::$(echo ${host})"
          if [[ ${host} == "pi-app-deployer-staging" ]]; then
            echo "::set-output name=PI_APP_DEPLOYER_API_KEY::$(echo ${PI_APP_DEPLOYER_API_KEY_STAGING})"
          else
            echo "::set-output name=PI_APP_DEPLOYER_API_KEY::$(echo ${PI_APP_DEPLOYER_API_KEY_PROD})"
          fi
      - name: Deploy Application
        uses: andrewmarklloyd/pi-app-deployer-action@main
        env:
          PI_APP_DEPLOYER_API_KEY: ${{ steps.vars.outputs.PI_APP_DEPLOYER_API_KEY }}
        with:
          repoName: andrewmarklloyd/pi-test
          manifestName: pi-test-amd64
          host: https://${{ steps.vars.outputs.DEPLOYER_HOST }}.herokuapp.com
