name: Main Build

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: make build
      - name: Run vet & lint
        run: |
          uname -m
          go env GOOS GOARCH
          go vet .
          golint .
      # - name: TODO add manifest validation
      - uses: actions/upload-artifact@v2
        with:
          name: app_${{ github.sha }}
          path: |
            # todo: get the executable from the manifest
            pi-test-agent-arm
            pi-test-agent-amd64
            .pi-app-deployer.yaml
