name: Main

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: make build
      - name: Run vet & lint
        run: |
          go vet .
          golint .
      - uses: actions/upload-artifact@v2
        with:
          name: "${GITHUB_SHA}_app"
          path: ./pi-test
      # send notification that asset is uploaded. need to get url, otherwise server will have to query and find it
      - name: Trigger pi-app-updater
        run: |
          echo $GITHUB_ACTION
          echo $GITHUB_ACTION_REPOSITORY
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_JOB
          echo $GITHUB_REF
          echo $GITHUB_REPOSITORY
          echo $GITHUB_RUN_ID
          echo $GITHUB_SHA


# curl -X POST -d '{"artifact":"${GITHUB_SHA}_app"}' https://pi-app-updater.herokuapp.com/cool-things
