name: Main Deploy

on:
  workflow_run:
    workflows: ["Main Build"]
    branches: [main]
    types: 
      - completed

jobs:
  pi_app_deployer:
    runs-on: ubuntu-latest
    name: Pi App Deployer
    steps:
      - name: Get deployer host
        run: |
          line=$(tail -n 1 test/integration-trigger.txt)
          arr=($(echo $line | tr ";" "\n"))
          echo ::set-output name=DEPLOYER_HOST::$(echo ${arr[2]})
      - name: Deploy Application
        uses: andrewmarklloyd/pi-app-deployer-action@main
        env:
          PI_APP_DEPLOYER_API_KEY: ${{ secrets.PI_APP_DEPLOYER_API_KEY }}
        with:
          repoName: andrewmarklloyd/pi-test
          manifestName: pi-test-amd64
          host: https://${{ steps.vars.outputs.DEPLOYER_HOST }}.herokuapp.com
