name: Main Deploy

on:
  workflow_run:
    workflows: ["Main Build"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy
        env:
          PI_APP_DEPLOYER_API_KEY: ${{ secrets.PI_APP_DEPLOYER_API_KEY }}
        run: |
          response=$(curl -s -X POST -H "api-key: ${PI_APP_DEPLOYER_API_KEY}" -d '{"sha":"${{ github.sha }}","repository":"${{ github.repository }}","name":"app_${{ github.sha }}","manifest_name":"pi-test-arm"}' https://pi-app-deployer.herokuapp.com/push)
          echo ${response}
          if [[ $(echo ${response} | jq -r '.status') != "success" ]]; then echo ${response};exit 1; fi
