on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Deployer
    steps:
      - name: Hello world action step
        id: hello
        uses: andrewmarklloyd/pi-app-deployer-action@v2
