name: Deploy

on: [push]

jobs:
  pi_app_deployer:
    runs-on: ubuntu-latest
    name: Pi App Deployer
    steps:
      - name: Deploy Application
        uses: andrewmarklloyd/pi-app-deployer-action@main
        env:
          PI_APP_DEPLOYER_API_KEY: ${{ secrets.PI_APP_DEPLOYER_API_KEY }}
